#!/usr/bin/env node
// SPDX-FileCopyrightText: 2026 MesTTo
//
// SPDX-License-Identifier: MIT
//
// Bounded benchmarks for async and parallel MeTTa TS surfaces. These are separate from the mitata hot-path
// suite because worker-thread hyperpose intentionally pays worker startup cost and should not be run with an
// adaptive microbenchmark iteration count.

import { format, gint, runProgramAsync } from "../../core/dist/index.js";
import {
  REGRESSION_MIN_MS,
  REGRESSION_RATIO,
  UPDATE,
  defaultConcurrencyReportPath,
  expectResults,
  lastResults,
  makeTimerAsyncOps,
  measureCases,
  renderTable,
  writeOrCheckReport,
} from "../../bench/concurrency-harness.mjs";
import { runSourceAsync } from "../dist/source.js";

const OUT = defaultConcurrencyReportPath(import.meta.url);

const asyncOps = makeTimerAsyncOps(gint);

async function checkedRunSource(name, source, expected, ops = asyncOps) {
  const results = await runSourceAsync(source, ops);
  expectResults(name, lastResults(results, format), expected);
}

async function checkedRunProgram(name, source, expected, ops = asyncOps) {
  const results = await runProgramAsync(source, ops);
  expectResults(name, lastResults(results, format), expected);
}

const concurrency = (source) => `!(import! &self concurrency)\n${source}`;

const HYPERPOSE_SOURCE = `
  (: one (-> Number))
  (= (one) 1)
  (: two (-> Number))
  (= (two) 1)
  (: three (-> Number))
  (= (three) 1)
  (: four (-> Number))
  (= (four) 1)
  !(once (hyperpose ((one) (two) (three) (four))))
`;

const CASES = [
  {
    name: "core runProgramAsync (+ 1 2)",
    runs: 21,
    run: () => checkedRunProgram("core runProgramAsync (+ 1 2)", "!(+ 1 2)", ["3"], new Map()),
  },
  {
    name: "node runSourceAsync (+ 1 2)",
    runs: 21,
    run: () => checkedRunSource("node runSourceAsync (+ 1 2)", "!(+ 1 2)", ["3"], new Map()),
  },
  {
    name: "par 4x resolved async op",
    runs: 21,
    run: () =>
      checkedRunSource(
        "par 4x resolved async op",
        concurrency("!(par (aw 0) (aw 0) (aw 0) (aw 0))"),
        ["0", "0", "0", "0"],
      ),
  },
  {
    name: "par 4x 2ms timer",
    runs: 9,
    run: () =>
      checkedRunSource("par 4x 2ms timer", concurrency("!(par (aw 2) (aw 2) (aw 2) (aw 2))"), [
        "2",
        "2",
        "2",
        "2",
      ]),
  },
  {
    name: "race slow/fast async op",
    runs: 13,
    run: () =>
      checkedRunSource("race slow/fast async op", concurrency("!(race (aw 5) (aw 0))"), ["0"]),
  },
  {
    name: "with-mutex 4x awaited sections",
    runs: 9,
    run: () =>
      checkedRunSource(
        "with-mutex 4x awaited sections",
        concurrency(
          "!(par (with-mutex L (aw 1)) (with-mutex L (aw 1)) (with-mutex L (aw 1)) (with-mutex L (aw 1)))",
        ),
        ["1", "1", "1", "1"],
      ),
  },
  {
    name: "with_mutex wrapper 4x awaited bodies",
    runs: 9,
    run: () =>
      checkedRunSource(
        "with_mutex wrapper 4x awaited bodies",
        concurrency(
          "!(par (with_mutex L (aw 1)) (with_mutex L (aw 1)) (with_mutex L (aw 1)) (with_mutex L (aw 1)))",
        ),
        ["1", "1", "1", "1"],
      ),
  },
  {
    name: "once hyperpose 4 pure branches",
    runs: 5,
    run: () =>
      checkedRunSource("once hyperpose 4 pure branches", HYPERPOSE_SOURCE, ["1"], new Map()),
  },
];

const rows = await measureCases(CASES);

function renderReport(data) {
  return `# MeTTa TS async and parallel benchmark

Generated by \`node packages/node/bench/concurrency.mjs\`. Absolute times are machine-specific; use this as a
same-machine regression reference for async source evaluation, cooperative \`par\`/\`race\`/\`with-mutex\`, the
PeTTa-compatible \`with_mutex\` wrapper, and Node worker-thread \`once (hyperpose ...)\`.

${renderTable(data)}
`;
}

writeOrCheckReport({
  rows,
  out: OUT,
  update: UPDATE,
  report: renderReport(rows),
  createCommand: "node packages/node/bench/concurrency.mjs --update",
  regressionRatio: REGRESSION_RATIO,
  regressionMinMs: REGRESSION_MIN_MS,
});
