#!/usr/bin/env node
// SPDX-FileCopyrightText: 2026 MesTTo
//
// SPDX-License-Identifier: MIT
//
// Bounded benchmarks for the browser source runner. These run under Node against the browser package build,
// so Web Worker startup is not measured here; a real browser benchmark owns that once the LSP browser harness
// is wired.

import { format, gint } from "../../core/dist/index.js";
import {
  REGRESSION_MIN_MS,
  REGRESSION_RATIO,
  UPDATE,
  defaultConcurrencyReportPath,
  expectResults,
  lastResults,
  makeTimerAsyncOps,
  measureCases,
  renderTable,
  writeOrCheckReport,
} from "../../bench/concurrency-harness.mjs";
import { run, runSourceAsync } from "../dist/source.js";

const OUT = defaultConcurrencyReportPath(import.meta.url);

const asyncOps = makeTimerAsyncOps(gint);

async function checkedRunSource(name, source, expected, ops = asyncOps, opts = undefined) {
  const results = await runSourceAsync(source, ops, undefined, new Map(), opts);
  expectResults(name, lastResults(results, format), expected);
}

function checkedRun(name, source, files, expected) {
  expectResults(name, lastResults(run(source, files), format), expected);
}

const concurrency = (source) => `!(import! &self concurrency)\n${source}`;

const HYPERPOSE_SOURCE = `
  (: two (-> Number))
  (= (two) 2)
  (: four (-> Number))
  (= (four) 4)
  !(once (hyperpose ((two) (four))))
`;

const CASES = [
  {
    name: "browser run VFS import",
    runs: 21,
    run: () =>
      checkedRun(
        "browser run VFS import",
        "!(import! &self math)\n!(double 21)",
        new Map([["math", "(= (double $x) (* 2 $x))"]]),
        ["42"],
      ),
  },
  {
    name: "browser runSourceAsync (+ 1 2)",
    runs: 21,
    run: () =>
      checkedRunSource("browser runSourceAsync (+ 1 2)", "!(+ 1 2)", ["3"], new Map()),
  },
  {
    name: "browser par 4x resolved async op",
    runs: 21,
    run: () =>
      checkedRunSource(
        "browser par 4x resolved async op",
        concurrency("!(par (aw 0) (aw 0) (aw 0) (aw 0))"),
        ["0", "0", "0", "0"],
      ),
  },
  {
    name: "browser race slow/fast async op",
    runs: 13,
    run: () =>
      checkedRunSource("browser race slow/fast async op", concurrency("!(race (aw 5) (aw 0))"), [
        "0",
      ]),
  },
  {
    name: "browser with-mutex 4x awaited sections",
    runs: 9,
    run: () =>
      checkedRunSource(
        "browser with-mutex 4x awaited sections",
        concurrency(
          "!(par (with-mutex L (aw 1)) (with-mutex L (aw 1)) (with-mutex L (aw 1)) (with-mutex L (aw 1)))",
        ),
        ["1", "1", "1", "1"],
      ),
  },
  {
    name: "browser async hyperpose hook",
    runs: 13,
    run: () =>
      checkedRunSource("browser async hyperpose hook", HYPERPOSE_SOURCE, ["77"], new Map(), {
        parEvalAsyncImpl: async () => [["77"], null],
      }),
  },
];

const rows = await measureCases(CASES);

function renderReport(data) {
  return `# MeTTa TS browser source benchmark

Generated by \`node packages/browser/bench/concurrency.mjs\`. Absolute times are machine-specific; use this as a
same-machine regression reference for the browser package source runner, VFS imports, async forms, and the
async hyperpose hook. Web Worker startup is covered by the LSP browser benchmark harness.

${renderTable(data)}
`;
}

writeOrCheckReport({
  rows,
  out: OUT,
  update: UPDATE,
  report: renderReport(rows),
  createCommand: "node packages/browser/bench/concurrency.mjs --update",
  regressionRatio: REGRESSION_RATIO,
  regressionMinMs: REGRESSION_MIN_MS,
  padWidth: 44,
});
