// SPDX-FileCopyrightText: 2026 MesTTo
//
// SPDX-License-Identifier: MIT

import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { format } from "prettier";

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const libraries = [
  "vector",
  "roman",
  "combinatorics",
  "patrick",
  "datastructures",
  "spaces",
  "nars",
  "pln",
];

const outDir = join(root, "src", "generated");
const outFile = join(outDir, "sources.ts");
const lines = [
  // The generated file needs its own SPDX header; these are text, not a license grant for this script.
  // REUSE-IgnoreStart
  "// SPDX-FileCopyrightText: 2026 MesTTo",
  "//",
  "// SPDX-License-Identifier: MIT",
  // REUSE-IgnoreEnd
  "",
  "// Generated by scripts/generate-sources.mjs. Do not edit.",
  "export const LIBRARY_MODULE_SRCS: Readonly<Record<string, string>> = {",
];

for (const name of libraries) {
  const src = readFileSync(join(root, "src", name, `${name}.metta`), "utf8");
  lines.push(`  ${name}: ${JSON.stringify(src)},`);
}

lines.push("};", "");
mkdirSync(outDir, { recursive: true });
writeFileSync(outFile, await format(lines.join("\n"), { parser: "typescript" }));
